# Generated by Django 3.1.3 on 2020-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed',
            field=models.TextField(verbose_name='embed'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
